#!/bin/bash

# Stop the script immediately if any command fails
set -e

echo "Running migrations..."
alembic upgrade head 

# Start Celery (using the deployment folder path)
echo "Starting Celery worker..."
./deployment/celery &

exec uvicorn src:app --host 0.0.0.0 --port 8000 --reload