"""Updated ticket db

Revision ID: 3354a247c318
Revises: b326dee8e6a5
Create Date: 2026-03-22 19:51:40.055966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3354a247c318'
down_revision: Union[str, Sequence[str], None] = 'b326dee8e6a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use op.execute to add values to the existing enum type
    # These must be executed independently in PostgreSQL for enums

    op.execute("ALTER TYPE issuetype ADD VALUE 'account_verification'")
    op.execute("ALTER TYPE issuetype ADD VALUE 'cards'")
    op.execute("ALTER TYPE issuetype ADD VALUE 'transfers'")
    op.execute("ALTER TYPE issuetype ADD VALUE 'integrations'")
    op.execute("ALTER TYPE issuetype ADD VALUE 'fees'")
    op.execute("ALTER TYPE issuetype ADD VALUE 'account_access'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
