"""Updated ticket table

Revision ID: b326dee8e6a5
Revises: b1d05c1501ee
Create Date: 2026-03-21 22:40:55.808713

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b326dee8e6a5'
down_revision: Union[str, Sequence[str], None] = 'b1d05c1501ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ticket', sa.Column('judge_tone_empathy', sa.Float(), nullable=True))
    op.add_column('ticket', sa.Column('judge_response_quality', sa.Float(), nullable=True))
    op.add_column('ticket', sa.Column('judge_faithfulness', sa.Float(), nullable=True))
    op.add_column('ticket', sa.Column('judge_groundedness', sa.Float(), nullable=True))
    op.add_column('ticket', sa.Column('judge_overall', sa.Float(), nullable=True))
    op.add_column('ticket', sa.Column('judge_pass', sa.Boolean(), nullable=True))
    op.add_column('ticket', sa.Column('judge_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('ticket', 'urgency',
               existing_type=postgresql.ENUM('high', 'medium', 'low', name='urgency'),
               nullable=True)
    op.alter_column('ticket', 'issue_type',
               existing_type=postgresql.ENUM('billing', 'technical', 'account', 'feature', 'general', name='issuetype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'issue_type',
               existing_type=postgresql.ENUM('billing', 'technical', 'account', 'feature', 'general', name='issuetype'),
               nullable=False)
    op.alter_column('ticket', 'urgency',
               existing_type=postgresql.ENUM('high', 'medium', 'low', name='urgency'),
               nullable=False)
    op.drop_column('ticket', 'judge_reason')
    op.drop_column('ticket', 'judge_pass')
    op.drop_column('ticket', 'judge_overall')
    op.drop_column('ticket', 'judge_groundedness')
    op.drop_column('ticket', 'judge_faithfulness')
    op.drop_column('ticket', 'judge_response_quality')
    op.drop_column('ticket', 'judge_tone_empathy')
    op.drop_column('ticket', 'name')
    # ### end Alembic commands ###
