"""Initial migration

Revision ID: cc223ecbf695
Revises: 
Create Date: 2026-03-22 20:37:04.882562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cc223ecbf695'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('plan_type', sa.Enum('free', 'premium', 'enterprise', name='plantype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('urgency', sa.Enum('high', 'medium', 'low', name='urgency'), nullable=True),
    sa.Column('issue_type', sa.Enum('account_verification', 'cards', 'transfers', 'integrations', 'fees', 'account_access', 'general', name='issuetype'), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('retrieval_score', sa.Float(), nullable=True),
    sa.Column('generated_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('llm_confidence', sa.Float(), nullable=True),
    sa.Column('semantic_similarity', sa.Float(), nullable=True),
    sa.Column('final_confidence', sa.Float(), nullable=True),
    sa.Column('routing_decision', sa.Enum('AUTO_RESOLVE', 'HUMAN_REVIEW', 'ESCALATE', name='routingdecision'), nullable=True),
    sa.Column('judge_tone_empathy', sa.Float(), nullable=True),
    sa.Column('judge_response_quality', sa.Float(), nullable=True),
    sa.Column('judge_faithfulness', sa.Float(), nullable=True),
    sa.Column('judge_groundedness', sa.Float(), nullable=True),
    sa.Column('judge_overall', sa.Float(), nullable=True),
    sa.Column('judge_pass', sa.Boolean(), nullable=True),
    sa.Column('judge_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('customer')
    # ### end Alembic commands ###
