"""Updated Ticker model by adding status field

Revision ID: f700abe46dbd
Revises: cc223ecbf695
Create Date: 2026-03-31 21:18:38.374977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f700abe46dbd'
down_revision: Union[str, Sequence[str], None] = 'cc223ecbf695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='status'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'status')
    # ### end Alembic commands ###
