from langchain_core.messages import HumanMessage, SystemMessage

from src.agents.confidence import ConfidenceCalculator
from src.agents.workflow_state import TicketState

# from src.agents.zendesk_client import (
#     assign_for_review,
#     escalate_ticket,
#     send_response_to_customer,
# )
from src.tickets.schemas import LLMProvider, RoutingDecision

# Celery runs as a separate process
# Initialize LLM (do this once, cached in Celery worker)

# llm = get_llm_client()


def _get_llm():
    """Lazy load LLM — only when first node runs, not at import time"""
    from src.agents.llm_config import get_llm_client

    return get_llm_client(LLMProvider.GROQ)


# Cache at module level after first call
llm = None


def get_llm():
    global llm
    if llm is None:
        llm = _get_llm()
    return llm


# NODE 1: Generate Response
def generate_response_node(state: TicketState) -> TicketState:
    """
    Uses LLM + RAG context to generate a response.
    """

    system_prompt = f"""
    You are Bella, a Raenest support agent.

    **Format**  
    - Start: "Hi, thanks for reaching out. I'm Bella."  
    - End: "Best Regards, Bella"  
    - After sign-off, add: "*This message was generated by Bella, our AI Agent*"  

    **Guidelines**  
    - Use knowledge base context. If context lacks an answer, state that honestly and proactively suggest escalation.  
    - For high urgency (payment delays, account lockouts, missing funds), show empathy and clearly indicate that you will escalate if the issue isn't resolved.  
    - When providing troubleshooting steps, include them from context. Add: "If the issue persists, reply and I'll escalate."  

    **Confidence** (0.0-1.0)  
    - 0.9-1.0: answer directly in context.  
    - 0.7-0.8: confident, may need verification.  
    - 0.5-0.6: low confidence; recommend escalation.  
    - <0.5: cannot answer; escalate.  
    
    Context from knowledge base:
    {state['rag_context']}
    
    Customer issue type: {state['classification']['issue_type']}
    Urgency: {state['classification']['urgency']}

    **Now answer the customer:**
    """

    user_message = f"""Subject: {state['subject']}
    
    Question: {state['description']}
    
    Please provide a helpful response. Also rate your confidence (0.0-1.0) 
    that this answer fully resolves the customer's issue."""

    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_message),
    ]

    response = llm.invoke(messages)

    state["generated_response"] = response.response
    state["llm_confidence"] = response.confidence

    return state


# NODE 2: Calculate Final Confidence
_confidence_calculator = ConfidenceCalculator()

# def calculate_confidence_node(state: TicketState) -> TicketState:
#     """
#     Implements the confidence formula:

#     confidence = (
#         0.4 * retrieval_score +
#         0.3 * semantic_similarity +
#         0.3 * llm_self_score
#     )

#     Updates state with:
#     - semantic_similarity
#     - final_confidence
#     """

#     # Calculate semantic similarity between query and retrieved docs

#     calc = _confidence_calculator
#     query = f"{state['subject']}. {state['description']}"

#     semantic_similarity = calc.calculate_similarity(query, state["rag_context"])

#     # Apply your formula
#     final_confidence = (
#         0.4 * state["retrieval_score"]
#         + 0.3 * semantic_similarity
#         + 0.3 * state["llm_confidence"]
#     )

#     state["semantic_similarity"] = semantic_similarity
#     state["final_confidence"] = final_confidence

#     return state


# NODE 2: Calculate Confidence — async because NVIDIA embeddings is async
async def calculate_confidence_node(state: TicketState) -> TicketState:
    query = f"{state['subject']}. {state['description']}"

    semantic_similarity = await _confidence_calculator.calculate_similarity(
        query, state["rag_context"]
    )

    final_confidence = (
        0.4 * state["retrieval_score"]
        + 0.3 * semantic_similarity
        + 0.3 * state["llm_confidence"]
    )

    state["semantic_similarity"] = semantic_similarity
    state["final_confidence"] = final_confidence

    return state


# NODE 3: Auto Resolve


async def auto_resolve_node(state: TicketState) -> TicketState:
    """
    Sends response to customer automatically via Zendesk API.
    Also stores the ticket+response in knowledge base (feedback loop).

    Updates state with:
    - routing_decision = "auto_resolve"
    """

    # await send_response_to_customer(
    #     ticket_id=state["ticket_id"],
    #     response=state["generated_response"],
    #     urgency=state["classification"]["urgency"],
    #     issue_type=state["classification"]["issue_type"],
    # )

    state["routing_decision"] = RoutingDecision.AUTO_RESOLVE

    return state


# NODE 4: Human Review


async def human_review_node(state: TicketState) -> TicketState:
    """
    Assigns ticket to human for review before sending.
    Updates Zendesk with internal note containing draft response.
    """

    # await assign_for_review(
    #     ticket_id=state["ticket_id"],
    #     draft_response=state["generated_response"],
    #     confidence=state["final_confidence"],
    #     issue_type=state["classification"]["issue_type"],
    #     urgency=state["classification"]["urgency"],
    # )

    state["routing_decision"] = RoutingDecision.HUMAN_REVIEW

    return state


# NODE 5: Escalate


async def escalate_node(state: TicketState) -> TicketState:
    """
    Escalates to specialist team based on issue type.
    """

    # await escalate_ticket(
    #     ticket_id=state["ticket_id"],
    #     issue_type=state["classification"]["issue_type"],
    #     attempted_response=state["generated_response"],
    #     confidence=state["final_confidence"],
    #     urgency=state["classification"]["urgency"],
    # )

    state["routing_decision"] = RoutingDecision.ESCALATE

    return state


def route_by_confidence(state: TicketState) -> str:
    """
    Routes to next node based on confidence score.

    Returns:
    - "auto_resolve" if confidence > 0.85
    - "human_review" if 0.6 <= confidence <= 0.85
    - "escalate" if confidence < 0.6
    """

    confidence = state["final_confidence"]

    if confidence > 0.85:
        return "auto_resolve"
    elif confidence >= 0.6:
        return "human_review"
    else:
        return "escalate"
