from langchain.messages import ToolMessage
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.tools import tool

from src.agents.confidence import ConfidenceCalculator
from src.agents.workflow_state import TicketState

# from src.agents.zendesk_client import (
#     assign_for_review,
#     escalate_ticket,
#     send_response_to_customer,
# )
from src.tickets.schemas import LLMProvider, RoutingDecision
from src.tools.kyc_status import KYCStatusInput, check_kyc_status

# Celery runs as a separate process
# Initialize LLM (do this once, cached in Celery worker)

# llm = get_llm_client()


def _get_llm():
    """Lazy load LLM — only when first node runs, not at import time"""
    from src.agents.llm_config import get_llm_client

    llm = get_llm_client(LLMProvider.GROQ)
    return llm.bind_tools(tools)


# Cache at module level after first call
llm = None


def get_llm():
    global llm
    if llm is None:
        llm = _get_llm()
    return llm


@tool(args_schema=KYCStatusInput)
def check_kyc_status_tool(email: str, refresh_from_veriff: bool = False) -> dict:
    """
    Returns the current KYC verification status for a given user's email.
    Use this tool if the customer is asking about their verification status,
    why their account is on hold, or anything related to KYC.
    """
    return check_kyc_status(email, refresh_from_veriff)


# Create a list of all tools the agent can use
tools = [check_kyc_status_tool]


# NODE 1: Generate Response
def generate_response_node(state: TicketState) -> TicketState:
    """
    Uses LLM + RAG context to generate a response.
    """

    llm_with_tools = get_llm()

    customer_email = state.get("email")

    system_prompt = f"""
    You are Bella, a Raenest support agent. You have access to a knowledge base and a set of tools to help customers.
    The customer's email is: {customer_email}

    **Format**  
    - Start: "Hi, thanks for reaching out. I'm Bella."  
    - End: "Best Regards, Bella"  
    - After sign-off, add: "*This message was generated by Bella, our AI Agent*"  

    **Guidelines**  
    - First, decide if you have enough information to answer. If not, use a tool.
    - For KYC-related questions (e.g., "why is my account on hold?", "what's my verification status?"), you MUST use the `check_kyc_status_tool`.
    - After using a tool, use its output to formulate your final answer.
    - If the knowledge base context lacks an answer, state that honestly and suggest escalation.
    - For high urgency (payment delays, account lockouts, missing funds), show empathy and clearly indicate that you will escalate if the issue isn't resolved.  
    - When providing troubleshooting steps, include them from context. Add: "If the issue persists, reply and I'll escalate."  

    **Confidence** (0.0-1.0)  
    - 0.9-1.0: answer directly in context.  
    - 0.7-0.8: confident, may need verification.  
    - 0.5-0.6: low confidence; recommend escalation.  
    - <0.5: cannot answer; escalate.  
    
    Context from knowledge base:
    {state['rag_context']}
    
    Customer issue type: {state['classification']['issue_type']}
    Urgency: {state['classification']['urgency']}

    **Now answer the customer:**
    """

    user_message = f"""Subject: {state['subject']}
    
    Question: {state['description']}
    
    Please provide a helpful response. Also rate your confidence (0.0-1.0) 
    that this answer fully resolves the customer's issue."""

    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_message),
    ]

    response = llm.invoke(messages)

    if response.tool_calls:
        print(f"LLM decided to use a tool: {response.tool_calls[0]['name']}")

        tool_call = response.tool_calls[0]
        tool_to_use = {t.name: t for t in tools}[tool_call["name"]]

        tool_output = tool_to_use.invoke(tool_call["args"])

        messages.append(response)
        messages.append(
            ToolMessage(content=str(tool_output), tool_call_id=tool_call["id"])
        )

        print("🗣️ Feeding tool output back to LLM for final response...")
        final_response = llm_with_tools.invoke(messages)

        state["generated_response"] = final_response.content
        # You might want a more robust way to get confidence after a tool call
        state["llm_confidence"] = response.confidence
    else:
        print("🤖 LLM responded directly without using a tool.")
        state["generated_response"] = response.response
        state["llm_confidence"] = response.confidence

    return state


# NODE 2: Calculate Final Confidence
_confidence_calculator = ConfidenceCalculator()


# NODE 2: Calculate Confidence — async because NVIDIA embeddings is async
async def calculate_confidence_node(state: TicketState) -> TicketState:
    """
    Implements the confidence formula:

     confidence = (
         0.4 * retrieval_score +
         0.3 * semantic_similarity +
         0.3 * llm_self_score
     )

     Updates state with:
     - semantic_similarity
     - final_confidence
    """
    query = f"{state['subject']}. {state['description']}"

    semantic_similarity = await _confidence_calculator.calculate_similarity(
        query, state["rag_context"]
    )

    final_confidence = (
        0.4 * state["retrieval_score"]
        + 0.3 * semantic_similarity
        + 0.3 * state["llm_confidence"]
    )

    state["semantic_similarity"] = semantic_similarity
    state["final_confidence"] = final_confidence

    return state


# NODE 3: Auto Resolve


async def auto_resolve_node(state: TicketState) -> TicketState:
    """
    Sends response to customer automatically via Zendesk API.
    Also stores the ticket+response in knowledge base (feedback loop).

    Updates state with:
    - routing_decision = "auto_resolve"
    """

    # await send_response_to_customer(
    #     ticket_id=state["ticket_id"],
    #     response=state["generated_response"],
    #     urgency=state["classification"]["urgency"],
    #     issue_type=state["classification"]["issue_type"],
    # )

    state["routing_decision"] = RoutingDecision.AUTO_RESOLVE

    return state


# NODE 4: Human Review


async def human_review_node(state: TicketState) -> TicketState:
    """
    Assigns ticket to human for review before sending.
    Updates Zendesk with internal note containing draft response.
    """

    # await assign_for_review(
    #     ticket_id=state["ticket_id"],
    #     draft_response=state["generated_response"],
    #     confidence=state["final_confidence"],
    #     issue_type=state["classification"]["issue_type"],
    #     urgency=state["classification"]["urgency"],
    # )

    state["routing_decision"] = RoutingDecision.HUMAN_REVIEW

    return state


# NODE 5: Escalate


async def escalate_node(state: TicketState) -> TicketState:
    """
    Escalates to specialist team based on issue type.
    """

    # await escalate_ticket(
    #     ticket_id=state["ticket_id"],
    #     issue_type=state["classification"]["issue_type"],
    #     attempted_response=state["generated_response"],
    #     confidence=state["final_confidence"],
    #     urgency=state["classification"]["urgency"],
    # )

    state["routing_decision"] = RoutingDecision.ESCALATE

    return state


def route_by_confidence(state: TicketState) -> str:
    """
    Routes to next node based on confidence score.

    Returns:
    - "auto_resolve" if confidence > 0.85
    - "human_review" if 0.6 <= confidence <= 0.85
    - "escalate" if confidence < 0.6
    """

    confidence = state["final_confidence"]

    if confidence > 0.85:
        return "auto_resolve"
    elif confidence >= 0.6:
        return "human_review"
    else:
        return "escalate"
